---
title: "Concessão Florestal"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr, warn.conflicts = FALSE)
library(sf, warn.conflicts = FALSE)
library(tmap, warn.conflicts = FALSE)
library(leaflet)
library(DT)
```

```{r, include=FALSE}
source("D:/concessaoFlorestal/leaflet_map_flonas.R", local = knitr::knit_global())
source("D:/concessaoFlorestal/leaflet_map_umf.R", local = knitr::knit_global())
```

FLONAS
=============================
Column
-----------------------------------------------------------------------

### Florestas Nacionais sob Concessão

```{r}
flona_map
```

Column {data-width=100, data-orientaion=rows}
-----------------------------------------------------------------------
### PMFS
```{r}
valueBox(nrow(umf))
```

### Concecionárias
```{r}
valueBox(length(unique(umf$conces)) - 1)
```

### UPAs AUTORIZADAS
```{r}
valueBox(nrow(upas[upas$status == "Explorada" | upas$status == "Explorando", ]))
```

### Árvores Inventariadas
```{r}
fi <- readRDS("D:/CensoFlorestal/data/if_concessao_pa_clean.rds")

valueBox(prettyNum(nrow(fi), big.mark = "."))
```

### Espécies Inventariadas
```{r}
valueBox(prettyNum(length(unique(fi$Nome_Cientifico)), big.mark = "."))
```


UMF/UPA
=============================
Column
-----------------------------------------------------------------------

### Florestas Nacionais sob Concessão
```{r}
umf_map
```


TABELAS
=============================
Column
-----------------------------------------------------------------------

```{r}
flonas <- flonas_conces %>%
        select(nome, areaHa, anoCriacao, areaHa, atoLegal, UF, municipios)

datatable(
        flonas,
        caption = "Florestas Nacionais sob Concessão Pública.", 
        extensions = "Buttons",
        options = list(
                rownames = FALSE,
                pageLength = 6,
                dom = "Bfrtip",
                buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
        ),
        fillContainer = TRUE
)
```
> Fonte: ICMBio.
