---
title: 'Concessão Florestal'
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr, warn.conflicts = FALSE)
library(sf, warn.conflicts = FALSE)
library(tmap, warn.conflicts = FALSE)
library(leaflet)
library(DT)
```

```{r include=FALSE}
source('./leaflet_map_flonas.R', local = knitr::knit_global())
source('./leaflet_map_umf.R', local = knitr::knit_global())
```

FLONAS
=============================
Column
-----------------------------------------------------------------------

### Florestas Nacionais sob Concessão

```{r}
flona_map
```

Column {data-width=100, data-orientaion=rows}
-----------------------------------------------------------------------
### PMFS
```{r}
valueBox(nrow(umf))
```

### Concecionárias
```{r}
valueBox(length(unique(umf$conces)) - 1)
```

### UPAs AUTORIZADAS
```{r}
valueBox(nrow(upas[upas$status == 'Explorada' | upas$status == 'Explorando', ]))
```

### Árvores Inventariadas
```{r load_data}
fi <- readRDS('./output/data_clean/if_concessao_pa.rds')

valueBox(prettyNum(nrow(fi), big.mark = '.'))
```

### Espécies Inventariadas
```{r}
df <- fi %>% filter(
        nome_cientifico != "",
        !is.na(fi$nome_cientifico),
        !grepl('^(.*\\b[sp|spp]$).*', nome_cientifico)
)

ref_name <- data.frame(name = taxize::gnr_resolve(df$nome_cientifico, 
                    best_match_only = TRUE, 
                    canonical = TRUE)$matched_name2) %>%
        filter(grepl("^\\w+\\s\\b", name))

valueBox(prettyNum(length(unique(ref_name)), big.mark = '.'))
```


UMF/UPA
=============================
Column
-----------------------------------------------------------------------

### Florestas Nacionais sob Concessão
```{r}
umf_map
```


TABELAS
=============================
Column
-----------------------------------------------------------------------

```{r}
flonas <- flonas_conces %>%
        select(nome, areaHa, anoCriacao, areaHa, atoLegal, UF, municipios)


datatable(
        flonas,
        caption = 'Florestas Nacionais sob Concessão Pública.', 
        extensions = 'Buttons',
        options = list(
                rownames = FALSE,
                pageLength = 10,
                dom = "Bfrtip",
                buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese.json'),
                scrollY = '250px'
        ),
        fillContainer = TRUE
) %>%
        formatCurrency(
                columns = 'areaHa',
                currency = '',
                interval = 3,
                mark = '.',
                dec.mark = '.'
        )
```
> Fonte: ICMBio.
